### PR TITLE
Separate stage outputs

### PR DESCRIPTION
**Pull request by rarutter**

### CODE REVIEW

**Comment by tobeycarman** [comment]
Looks good. This will be handy. I haven't gotten to try it yet. You might note, that it will conflict with some of the changes I have in my recent "refac" branch. This is not problem, and I can rebase my branch if we merge this PR first.

**Comment by rarutter** [comment]
Ok, I'll take a look at that before I merge this.

**Comment by rarutter** [comment]
Yeah, it looks like the changes can be worked together, whether I merge and you rebase or vice versa. Do you have a strong preference either way?

**Comment by tobeycarman** [comment]
May as well merge this; that `refac` branch isn't quite ready yet.

**Pull request merged**
