### PR TITLE
Add code that can create .tar.gz archives of all calibration json files at the end of a stage.

### PR DESCRIPTION
**Pull request by tobeycarman**

### CODE REVIEW

**Comment by tobeycarman** [comment]
I am not sure that using the `system(..)` call is the best way to do this, but it has worked so far (I have been using it). I kind of dislike having less-than-perfect implementations like this sneak into the codebase, but it is useful, and saves a bunch of time on the output/post-processing side, so it'd be handy to have this merged in. 

One other issue I have with it is that I simply write the `*-data.tar.gz` files to `/tmp/`. I have then been manually moving them to my output-archive location. Maybe it would be better for the archives to be written to the current working directory? Or the directory where the `dmvdostem` executable lives? Or the `DATA/<run case>/output/` directory?

**Comment by rarutter** [comment]
If you don't use a `system()` call, it would require another library, which can cause other issues.

True, output dir is tricky. The point of the archives is usually for graphs, so does one directory or storage regime work better/easier than others for the plotter?

**Comment by tobeycarman** [comment]
re: other library, yeah that is another can of worms, and looks to involve quite a bit more programming.

re: output, I guess the most intuitive is to dump the archives in the same directory as the `dvmdostem` executable? The reason we put the calibration json files in `/tmp` was so that the user wouldn't have to remember to clean them up, but with the archives, the idea is to keep them, so that isn't so much an issue. I am not sure if I like the system of having the output directory that is buried w/in the `DATA/<run case>/` folders. Always seems to trip me up. I think it was setup that way to facilitate the restart data files maybe?

I also probably should have a routine that cleans up any existing archives so you don't run into a situation where you say only run one or two stages, but end up saving/looking at data that was lingering around from previous runs...

**Comment by rarutter** [comment]
In the toplevel `dvmdostem` executable directory sounds good to me.

**Comment by tobeycarman** [comment]
Hmm more complicated than I wanted it to be to get the location of the executable in a consistent portable manner...

http://stackoverflow.com/questions/1528298/get-path-of-executable

Maybe the `/tmp/` location will work for now...

**Comment by rarutter** [comment]
Hm, I hadn't thought through to that point. That is a pain, and risking
files being written to whatever random directory dvmdostem is called from
isn't good. For now, /tmp seems easiest?

**Pull request merged**
