### PR TITLE
Change units in output_spec.csv file to remove N and C...

### LINKED ISSUE #413: Remove element names from units strings in input and output netcdf
Currently we are using for example "kg C m-2 s-1", but in udunits, C is coulomb, not elemental Carbon! And N is for Newtons, not elemental Nitrogen. See here: https://www.unidata.ucar.edu/software/netcdf/netcdf-4/newdocs/netcdf/Units.html
 
We should change all the unit strings in the outpus_spec.csv file and possibly update a few of the variable names so it is abundantly clear what comprises the mass referred to in the units.

### PR DESCRIPTION
**Pull request by tobeycarman**
...which were used erroneously.

Fixes #413.

### CODE REVIEW

**Comment by tobeycarman** [comment]
This will require modifying the PEcAn dvmdostem wrappers.

**Comment by rarutter** [comment]
Did you want to modify those before this PR is resolved?

**Comment by serbinsh** [comment]
@tobeycarman do we need to update the PEcAn code, merge, and update dvm-dos-tem on modex to incorporate these changes?

**Comment by tobeycarman** [comment]
@serbinsh, yes, but not for these latest simulations (which are nearly done). Now that we have code depending on dvmdostem (PEcAn), we'll try to start using some kind of version tags and "releases".

So I tagged SHA 892154a as v0.1.0 and this is where I have done all the latest PEcAn dvmdostem work. Since then we have merged a bunch of stuff into `dvmdostem`'s master brnach (changes to science logic, changes to utility scripts, etc). Some of those changes modify the public interface of `dvmdostem` (i.e. the units specification and some other changes to the utility scripts). So right now PEcAn works with dvmdostem v0.1.0, and in order to work with v0.2.0, I'll have to make some more updates to the PEcAn dvmdostem wrapper code.

**Comment by serbinsh** [comment]
Hi @tobeycarman I think using tagged releases is a really good idea, particularly when you might go from one working version to another where any tool using the model might break between the two.  As such, can I assume that v0.1.0 is the version to use with PEcAn at this point?  If so I might update the BETY model table to give this as a specific model tag to use with PEcAn and if/when we update to a new tag we can then add another version of TEM to the BETY model table,.  This is way better for tracking and matching versions of the PEcAn wrappers with model version

**Comment by tobeycarman** [comment]
@serbinsh, yes, I have been meaning to start using tagged releases for a while.

Yes, v0.1.0 is the version to use with PEcAn at this point, and it would be excellent to update BETY to that effect. 

We are going to try to adhere to the 'semantic versioning' standard, but I anticipate it taking a bit to figure out. And I expect our "public interface" (which at this point is a hodge-podge utility scripts) to change rapidly, so for now, @rarutter and I figured we'd keep the dvmdostem version under v1.0.0 as the semantic versioning spec says that before you release v1.0.0, "any thing can happen" so we don't have to worry as much about bumping the wrong version number when we lose backward compatibility. So I expect to break the PEcAn integration moving forward, but at least with some named/tagged releases, we have a change at fixing it relatively quickly...

**Pull request merged**
