### PR TITLE
Improve logging scopes

### PR DESCRIPTION
**Pull request by tobeycarman**
Re-work the monthly and yearly checksumming code so that the logging scopes are more usable.

### CODE REVIEW

**Comment by rarutter** [comment]
For me, this segfaults at Runner.cpp:286. I'm taking a look at that now.

**Comment by tobeycarman** [comment]
Shoot. What stage? I have not gotten a seg fault yet, but I am not surprised. 

For me, during the pre-run, we still have some kind of bug where it is summing things over un-initialized values - so there are lots of checksumming errors. But during the equilibrium stage, the errors go away. 

```
[err] [PRE-RUN->Y->M] PFT:7 whole plant strn and plant strn PART not summing correctly! A: 0 B: 1.4155 (A-B: -1.4155)
[err] [PRE-RUN->Y->M] Runner:: ecosystem nall not matching sum over PFTs (of strn and nall)! A: 0 B: 1.332 (A-B: -1.332)
[err] [PRE-RUN->Y->M] Runner:: ecosystem strn not matching sum over compartments! A: 0 B: 25.308 (A-B: -25.308)
[err] [PRE-RUN->Y->M] ========== END MONTHLY CHECKSUMMING month: 11 year: 9 ============
[err] [PRE-RUN->Y->M] ========== YEARLY CHECKSUM ERRORS ============
[err] [PRE-RUN->Y->M] PFT:0 whole plant strn and plant strn PART not summing correctly! A: 0 B: 2.166 (A-B: -2.166)
[err] [PRE-RUN->Y->M] PFT:1 whole plant strn and plant strn PART not summing correctly! A: 0 B: 2.0615 (A-B: -2.0615)
[err] [PRE-RUN->Y->M] PFT:2 whole plant strn and plant strn PART not summing correctly! A: 0 B: 5.1395 (A-B: -5.1395)
[err] [PRE-RUN->Y->M] PFT:3 whole plant strn and plant strn PART not summing correctly! A: 0 B: 11.59 (A-B: -11.59)
[err] [PRE-RUN->Y->M] PFT:4 whole plant strn and plant strn PART not summing correctly! A: 0 B: 1.748 (A-B: -1.748)
[err] [PRE-RUN->Y->M] PFT:5 whole plant strn and plant strn PART not summing correctly! A: 0 B: 0.6555 (A-B: -0.6555)
[err] [PRE-RUN->Y->M] PFT:6 whole plant strn and plant strn PART not summing correctly! A: 0 B: 0.532 (A-B: -0.532)
[err] [PRE-RUN->Y->M] PFT:7 whole plant strn and plant strn PART not summing correctly! A: 0 B: 1.4155 (A-B: -1.4155)
[err] [PRE-RUN->Y->M] Runner:: ecosystem nall not matching sum over PFTs (of strn and nall)! A: 0 B: 1.332 (A-B: -1.332)
[err] [PRE-RUN->Y->M] Runner:: ecosystem strn not matching sum over compartments! A: 0 B: 25.308 (A-B: -25.308)
[err] [PRE-RUN->Y->M] ========== END YEARLY CHECKSUMMING year: 9 ============
[fatal] [EQ] Running Equilibrium, 10 years.
[err] [EQ->Y] Year loop, year: 0
[err] [EQ->Y->M->DIMgrd] Yi et al. 2009 says the b coefficient should be a fitted parameter constrained to >= 1!
[err] [EQ->Y->M->DIMgrd] Yi et al. 2009 says the b coefficient should be a fitted parameter constrained to >= 1!
[err] [EQ->Y->M->DIMgrd] Yi et al. 2009 says the b coefficient should be a fitted parameter constrained to >= 1!
[err] [EQ->Y->M->DIMgrd] Yi et al. 2009 says the b coefficient should be a fitted parameter constrained to >= 1!
[err] [EQ->Y->M->DIMgrd] Yi et al. 2009 says the b coefficient should be a fitted parameter constrained to >= 1!
[err] [EQ->Y->M->DIMgrd] Yi et al. 2009 says the b coefficient should be a fitted parameter constrained to >= 1!
[err] [EQ->Y->M->DIMgrd] Yi et al. 2009 says the b coefficient should be a fitted parameter constrained to >= 1!
[err] [EQ->Y->M->DIMgrd] Yi et al. 2009 says the b coefficient should be a fitted parameter constrained to >= 1!
[err] [EQ->Y->M->DIMgrd] Yi et al. 2009 says the b coefficient should be a fitted parameter constrained to >= 1!
[err] [EQ->Y->M->DIMgrd] Yi et al. 2009 says the b coefficient should be a fitted parameter constrained to >= 1!
[err] [EQ->Y] Year loop, year: 1
[err] [EQ->Y->M->DIMgrd] Yi et al. 2009 says the b coefficient should be a fitted parameter constrained to >= 1!
[err] [EQ->Y->M->DIMgrd] Yi et al. 2009 says the b coefficient should be a fitted parameter constrained to >= 1!
[err] [EQ->Y->M->DIMgrd] Yi et al
```

Then in later stages, the errors come back, but only for the higher number (unused) PFTs, so I think there is something about how we are reading data from the back in from the RestartData objects for the un-used (Misc) PFTs.

**Comment by rarutter** [comment]
Called with
`./dvmdostem -c -l debug -p 1 -e 1 -s 0`

The last section of logging is
```
[debug] [PRE-RUN->Y->M] Clean up at the end of the month
[debug] [PRE-RUN->Y->M] Soil aggregation at end of month
[debug] [PRE-RUN->Y->M] Synchronize the RestartData object with the model's state...
[note] [PRE-RUN->Y->M] Updating this Cohort's restartdata member with values from the model's state (various fields of  Cohort and CohortData).
[debug] [PRE-RUN->Y->M] TODO: ouput some data!
[debug] [PRE-RUN->Y->M] Write monthly data to json files...
Segmentation fault
```
`it` isn't null, but its _M_node is.

Yeah, I'm not surprised there might be some oddities on unused PFTs. Something to be added to the list...

**Comment by tobeycarman** [comment]
Wow, I can't reproduce that on my computer.

**Comment by tobeycarman** [comment]
Ah ha, I am able to reproduce this on a Fedora VM. Will try to address the issue now that I have made it happen.

**Comment by tobeycarman** [comment]
OK, just pushed a fix. The problem was my hasty attempt and erasing empty strings from the list. New approach uses `std::remove_if(..)`. It is working for me on my Fedora VM.

**Comment by rarutter** [comment]
Awesome! I figured it had something to do with the erase() call, but got sidetracked onto something else. It runs fine for me as well now.

**Pull request merged**
